version: '3'
services:
    web:
        build: .
        ports:
            - '3000:3000'
        volumes:
            - '.:/ServerB'
        tty: true
        stdin_open: true
        depends_on:
            - selenium_chrome
    selenium_chrome:
        image: selenium/standalone-chrome-debug
        logging:
            driver: none
        ports:
            - 4444:4444